### ISSUE TITLE
Crash when a botania flower places block

### ISSUE THREAD

**Issue by delishoes** [absolutelyaya/ultracraft#127]
When I tried to make the "Rannuncarpus" flower from botania place blocks with ultracraft installed, the game crashed, providing this error:
```
[17:53:39] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_7338()" because "player" is null
	at absolutelyaya.ultracraft.components.world.DimensionDataComponent.isPosNotModifiable(DimensionDataComponent.java:102) ~[ultracraft-1.20.1-2.1.2b.jar:?]
	at net.minecraft.class_1747.handler$ccg000$ultracraft$onPlace(class_1747.java:1018) ~[server-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java) ~[server-intermediary.jar:?]
	at vazkii.botania.common.block.flower.functional.RannuncarpusBlockEntity.tickFlower(RannuncarpusBlockEntity.java:118) ~[Botania-1.20.1-443-FABRIC.jar:?]
	at vazkii.botania.api.block_entity.SpecialFlowerBlockEntity.commonTick(SpecialFlowerBlockEntity.java:99) ~[Botania-1.20.1-443-FABRIC.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more
```

**Comment by delishoes** [comment]
fixed :D
