### ISSUE TITLE
Random server crash while trying to shoot an enderman with a revolver (i utterly missed)

### ISSUE THREAD

**Issue by delishoes** [absolutelyaya/ultracraft#99]
[16:03:35] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.equals(Object)" because the return value of "net.minecraft.class_6025.method_35057()" is null
	at absolutelyaya.ultracraft.util.AutoAimUtil.lambda$getPotentialTargets$0(AutoAimUtil.java:78) ~[ultracraft-1.20.1-2.0.3.jar:?]
	at net.minecraft.class_1937.method_31593(class_1937.java:659) ~[server-intermediary.jar:?]
	at net.minecraft.class_7927.method_47542(class_7927.java:25) ~[server-intermediary.jar:?]
	at net.minecraft.class_5572.method_31765(class_5572.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_5573.method_39465(class_5573.java:122) ~[server-intermediary.jar:?]
	at net.minecraft.class_5573.method_31777(class_5573.java:65) ~[server-intermediary.jar:?]
	at net.minecraft.class_5573.method_31783(class_5573.java:122) ~[server-intermediary.jar:?]
	at net.minecraft.class_5578.method_31807(class_5578.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_8333(class_1937.java:658) ~[server-intermediary.jar:?]
	at absolutelyaya.ultracraft.util.AutoAimUtil.getPotentialTargets(AutoAimUtil.java:75) ~[ultracraft-1.20.1-2.0.3.jar:?]
	at absolutelyaya.ultracraft.util.AutoAimUtil.getTarget(AutoAimUtil.java:29) ~[ultracraft-1.20.1-2.0.3.jar:?]
	at absolutelyaya.ultracraft.ServerHitscanHandler$ScheduledHitscan.perform(ServerHitscanHandler.java:335) ~[ultracraft-1.20.1-2.0.3.jar:?]
	at absolutelyaya.ultracraft.ServerHitscanHandler.tickSchedule(ServerHitscanHandler.java:71) ~[ultracraft-1.20.1-2.0.3.jar:?]
	at absolutelyaya.ultracraft.Ultracraft.lambda$onInitialize$3(Ultracraft.java:85) ~[ultracraft-1.20.1-2.0.3.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-3792d0d4b63e847b.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zdh001$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:2862) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by absolutelyaya** [comment]
That crash was fixed in v2.0.4; updating to that version should prevent this from happening again

**Comment by crazyapple526** [comment]
I uhh, have 2.0.4 installed
